<% adapter = ENV.fetch('DB_ADAPTER', 'sqlite3') %>

default: &default
  adapter: <%= adapter %>
  encoding: utf8

<% if adapter == 'sqlite3' %>
  database: db/<%= ENV['RAILS_ENV'] %>.sqlite3

<% elsif adapter == 'mysql2' %>
  username: root
  database: ajax_datatables_rails

<% elsif adapter == 'postgresql' %>
  database: ajax_datatables_rails

<% elsif adapter == 'oracle_enhanced' %>
  username: ENV['USER']
  password: ENV['USER']
  database: xe
  host: 127.0.0.1/xe

<% end %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
