source 'https://rubygems.org'

gem 'rails'
gem 'puma'
gem 'sqlite3'
gem 'haml'
gem 'jquery-rails'
gem 'bootstrap-sass'
gem 'sass-rails'
gem 'coffee-rails'
gem 'font-awesome-sass'

# Add factory_girl to generate sample data
gem 'factory_girl'
gem 'faker'

gem 'ajax-datatables-rails', path: '../..'
